namespace MercadoPago.Resource.AdvancedPayment
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Represents a single split payment within an <see cref="AdvancedPayment"/>.
    /// Each split payment corresponds to one portion of the payer's total transaction,
    /// including payment method details, amounts, and installment configuration.
    /// </summary>
    public class AdvancedPaymentSplitPayment
    {
        /// <summary>
        /// Unique identifier of the split payment, assigned by MercadoPago.
        /// </summary>
        public long? Id { get; set; }

        /// <summary>
        /// Current status of this split payment. Indicates whether the payment was approved,
        /// rejected, or is pending. See <see cref="AdvancedPaymentStatus"/> for possible values.
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// Detailed reason for the current status, providing additional context
        /// about approvals, rejections, or pending states (e.g., <c>accredited</c>, <c>cc_rejected_other_reason</c>).
        /// </summary>
        public string StatusDetail { get; set; }

        /// <summary>
        /// Payment reason or item title describing the purpose of this split payment.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// External reference ID assigned by the merchant in their own system.
        /// Used to reconcile this split payment with internal records.
        /// </summary>
        public string ExternalReference { get; set; }

        /// <summary>
        /// Text that will appear on the payer's credit card statement for this charge.
        /// </summary>
        public string StatementDescriptor { get; set; }

        /// <summary>
        /// Payment type identifier (e.g., <c>credit_card</c>, <c>debit_card</c>, <c>ticket</c>).
        /// </summary>
        public string PaymentTypeId { get; set; }

        /// <summary>
        /// Identifier of the payment method chosen by the payer (e.g., <c>visa</c>, <c>master</c>, <c>pix</c>).
        /// </summary>
        public string PaymentMethodId { get; set; }

        /// <summary>
        /// Identifier of the specific payment method option selected, when multiple options exist for a payment method.
        /// </summary>
        public string PaymentMethodOptionId { get; set; }

        /// <summary>
        /// Processing mode that determines whether a specific merchant ID should be used.
        /// Common values: <c>aggregator</c>, <c>gateway</c>.
        /// </summary>
        public string ProcessingMode { get; set; }

        /// <summary>
        /// Identifier of the card issuer (bank or financial institution) for card-based payments.
        /// </summary>
        public string IssuerId { get; set; }

        /// <summary>
        /// Tokenized card data generated by MercadoPago's card tokenization process.
        /// Represents the payer's card information in a secure, non-sensitive format.
        /// </summary>
        public string Token { get; set; }

        /// <summary>
        /// Total amount charged for this split payment, in the transaction currency.
        /// </summary>
        public decimal? TransactionAmount { get; set; }

        /// <summary>
        /// Net amount received by the seller after fees and deductions are applied.
        /// </summary>
        public decimal? NetAmount { get; set; }

        /// <summary>
        /// Number of installments selected by the payer for this split payment.
        /// </summary>
        public int? Installments { get; set; }

        /// <summary>
        /// Expiration date and time for this split payment. After this date,
        /// the payment can no longer be completed if still pending.
        /// </summary>
        public DateTime? DateOfExpiration { get; set; }

        /// <summary>
        /// Discount amount applied via a coupon for this split payment.
        /// </summary>
        public decimal? CouponAmount { get; set; }

        /// <summary>
        /// Identifier of the discount campaign associated with this split payment.
        /// </summary>
        public int? CampaignId { get; set; }

        /// <summary>
        /// Coupon code entered by the payer to apply a discount campaign.
        /// </summary>
        public string CouponCode { get; set; }

        /// <summary>
        /// Merchant account identifier used for complex payment routing in gateway processing mode.
        /// </summary>
        public string MerchantAccountId { get; set; }

        /// <summary>
        /// Detailed transaction information including the total paid amount and external resource URL.
        /// </summary>
        public AdvancedPaymentTransactionDetails TransactionDetails { get; set; }

        /// <summary>
        /// List of taxes applied to this split payment. Each <see cref="AdvancedPaymentTax"/>
        /// specifies a tax type and its value.
        /// </summary>
        public IList<AdvancedPaymentTax> Taxes { get; set; }
    }
}
