namespace MercadoPago.Resource.AuthorizedPayment
{
    using System;
    using MercadoPago.Http;

    /// <summary>
    /// Represents an authorized payment (also known as an invoice) returned by
    /// the MercadoPago Subscriptions API. Each invoice is automatically
    /// generated by the recurrence engine for a
    /// <see cref="PreApproval.Preapproval"/> and tracks the collection attempt
    /// and its outcome. Use
    /// <see cref="Client.AuthorizedPayment.AuthorizedPaymentClient"/> to
    /// retrieve and search authorized payments.
    /// </summary>
    /// <remarks>
    /// For more information check the documentation
    /// <a href="https://www.mercadopago.com.br/developers/en/reference/subscriptions/resource/">here</a>
    /// </remarks>
    public class AuthorizedPayment : IResource
    {
        /// <summary>
        /// Unique identifier of this authorized payment (invoice).
        /// </summary>
        public long? Id { get; set; }

        /// <summary>
        /// Type of invoice generated based on the recurrence model.
        /// <list type="bullet">
        ///   <item><c>scheduled</c>: Automatically generated and scheduled by the recurrence engine.</item>
        /// </list>
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// Date and time when this authorized payment was created (UTC).
        /// </summary>
        public DateTimeOffset? DateCreated { get; set; }

        /// <summary>
        /// Date and time of the last modification to this authorized payment (UTC).
        /// </summary>
        public DateTimeOffset? LastModified { get; set; }

        /// <summary>
        /// Identifier of the <see cref="PreApproval.Preapproval"/> (subscription)
        /// for which this invoice was created.
        /// </summary>
        public string PreapprovalId { get; set; }

        /// <summary>
        /// Short description visible to the subscriber during checkout and in
        /// payment notifications.
        /// </summary>
        public string Reason { get; set; }

        /// <summary>
        /// Free-text external reference used to correlate this invoice with
        /// entities in your own system.
        /// </summary>
        public string ExternalReference { get; set; }

        /// <summary>
        /// ISO 4217 currency code used for the payment amount.
        /// <list type="bullet">
        ///   <item><c>ARS</c>: Argentine peso.</item>
        ///   <item><c>BRL</c>: Brazilian real.</item>
        ///   <item><c>CLP</c>: Chilean peso.</item>
        ///   <item><c>MXN</c>: Mexican peso.</item>
        ///   <item><c>COP</c>: Colombian peso.</item>
        ///   <item><c>PEN</c>: Peruvian sol.</item>
        ///   <item><c>UYU</c>: Uruguayan peso.</item>
        /// </list>
        /// </summary>
        public string CurrencyId { get; set; }

        /// <summary>
        /// Amount charged (or to be charged) for this invoice.
        /// </summary>
        public decimal TransactionAmount { get; set; }

        /// <summary>
        /// Scheduled date on which MercadoPago will attempt to collect payment.
        /// </summary>
        public DateTimeOffset? DebitDate { get; set; }

        /// <summary>
        /// Current lifecycle status of the authorized payment.
        /// <list type="bullet">
        ///     <item><c>scheduled</c>: Authorized payment scheduled for collection.</item>
        ///     <item><c>processed</c>: Authorized payment collected or retries exhausted.</item>
        ///     <item><c>recycling</c>: Authorized payment in a retry collection attempt.</item>
        ///     <item><c>cancelled</c>: Authorized payment has been cancelled.</item>
        /// </list>
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// Number of collection retry attempts made so far for this invoice.
        /// </summary>
        public int? RetryAttempt { get; set; }

        /// <summary>
        /// Indicates whether the invoice result has been summarized in the
        /// parent subscription.
        /// <list type="bullet">
        ///   <item><c>pending</c>: Summary has not yet been applied.</item>
        ///   <item><c>done</c>: Result has been summarized in the subscription.</item>
        /// </list>
        /// </summary>
        public string Summarized { get; set; }

        /// <summary>
        /// Payment information associated with this invoice, including the
        /// payment identifier and its processing status.
        /// </summary>
        public AuthorizedPaymentStatus Payment { get; set; }

        /// <summary>
        /// Raw HTTP response returned by the MercadoPago API for the request
        /// that produced this resource.
        /// </summary>
        public MercadoPagoResponse ApiResponse { get; set; }
    }
}
