namespace MercadoPago.Client.AdvancedPayment
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Represents a single payment instrument used by the buyer within an advanced payment.
    /// An advanced payment may contain multiple split payments when the buyer pays
    /// with more than one card or payment method.
    /// </summary>
    /// <see cref="AdvancedPaymentCreateRequest"/>
    public class AdvancedPaymentSplitPaymentRequest
    {
        /// <summary>
        /// Payment reason or short description shown to the payer during checkout.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Unique reference identifier assigned by the merchant in their own system for reconciliation.
        /// </summary>
        public string ExternalReference { get; set; }

        /// <summary>
        /// Text that will appear on the payer's credit card or bank statement (soft descriptor).
        /// </summary>
        public string StatementDescriptor { get; set; }

        /// <summary>
        /// Type of payment method (e.g., <c>"credit_card"</c>, <c>"debit_card"</c>, <c>"ticket"</c>).
        /// </summary>
        public string PaymentTypeId { get; set; }

        /// <summary>
        /// Identifier of the specific payment method chosen by the payer (e.g., <c>"visa"</c>, <c>"master"</c>).
        /// </summary>
        public string PaymentMethodId { get; set; }

        /// <summary>
        /// Identifier of a specific payment method option, when multiple options exist for the same method.
        /// </summary>
        public string PaymentMethodOptionId { get; set; }

        /// <summary>
        /// Processing mode that determines whether a specific merchant account is used.
        /// Typically <c>"aggregator"</c> or <c>"gateway"</c>.
        /// </summary>
        public string ProcessingMode { get; set; }

        /// <summary>
        /// Identifier of the card issuer (e.g., a specific bank). Required for certain payment methods.
        /// </summary>
        public string IssuerId { get; set; }

        /// <summary>
        /// Tokenized card data generated by MercadoPago's card tokenization service.
        /// Required for card-based payments.
        /// </summary>
        public string Token { get; set; }

        /// <summary>
        /// Total transaction amount for this split payment, in the payment currency. Must be greater than zero.
        /// </summary>
        public decimal? TransactionAmount { get; set; }

        /// <summary>
        /// Net amount received after deducting fees and financing costs.
        /// </summary>
        public decimal? NetAmount { get; set; }

        /// <summary>
        /// Number of installments selected by the payer. Must be 1 or greater.
        /// </summary>
        public int? Installments { get; set; }

        /// <summary>
        /// Date and time after which this payment can no longer be processed.
        /// Applicable to offline payment methods such as boleto or payment tickets.
        /// </summary>
        public DateTime? DateOfExpiration { get; set; }

        /// <summary>
        /// Discount amount applied via a coupon, deducted from the transaction amount.
        /// </summary>
        public decimal? CouponAmount { get; set; }

        /// <summary>
        /// Identifier of the discount campaign associated with this payment.
        /// </summary>
        public int? CampaignId { get; set; }

        /// <summary>
        /// Coupon code entered by the payer to apply a discount campaign.
        /// </summary>
        public string CouponCode { get; set; }

        /// <summary>
        /// Merchant account identifier used in gateway processing mode for complex payment scenarios.
        /// </summary>
        public string MerchantAccountId { get; set; }

        /// <summary>
        /// Additional details about the transaction, such as external resource URLs.
        /// </summary>
        /// <see cref="AdvancedPaymentTransactionDetailsRequest"/>
        public AdvancedPaymentTransactionDetailsRequest TransactionDetails { get; set; }

        /// <summary>
        /// List of tax charges applied to this split payment.
        /// </summary>
        /// <see cref="AdvancedPaymentTaxRequest"/>
        public IList<AdvancedPaymentTaxRequest> Taxes { get; set; }
    }
}
