using System;
namespace MercadoPago.Client.Payment
{
    /// <summary>
    /// 3D Secure (3DS) authentication data for a payment within <see cref="PaymentDataRequest"/>.
    /// Contains cryptographic and transaction identifiers verified by a third-party
    /// authentication provider, enabling external 3DS flows.
    /// </summary>
    public class PaymentAuthenticationRequest
    {
        /// <summary>
        /// Authentication type (e.g., "external_threeds").
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// Cryptogram (CAVV/AAV) generated by the 3DS authentication process.
        /// </summary>
        public string Cryptogram { get; set; }

        /// <summary>
        /// 3DS Server transaction identifier assigned during the authentication.
        /// </summary>
        public string ThreeDsServerTransId { get; set; }

        /// <summary>
        /// Electronic Commerce Indicator (ECI) value returned by the authentication.
        /// Indicates the level of authentication achieved (e.g., "05" for fully authenticated).
        /// </summary>
        public string Eci { get; set; }

        /// <summary>
        /// Directory Server (DS) transaction identifier from the 3DS protocol.
        /// </summary>
        public string DsTransId { get; set; }

        /// <summary>
        /// Access Control Server (ACS) transaction identifier from the 3DS protocol.
        /// </summary>
        public string AcsTransId { get; set; }

        /// <summary>
        /// 3DS protocol version used for the authentication (e.g., "2.1.0", "2.2.0").
        /// </summary>
        public string ThreeDsVersion { get; set; }

        /// <summary>
        /// Authentication status result (e.g., "Y" for authenticated, "A" for attempted,
        /// "N" for not authenticated, "U" for unavailable).
        /// </summary>
        public string AuthenticationStatus { get; set; }
    }
}

