namespace MercadoPago.Client.Payment
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Request payload for creating a new payment through the MercadoPago Payments API.
    /// Contains all fields needed to process a payment, including payer details, amount,
    /// payment method, and optional additional information.
    /// </summary>
    /// <remarks>
    /// Check the parameters
    /// <a href="https://www.mercadopago.com/developers/en/reference/payments/_payments/post/">here</a>.
    /// </remarks>
    public class PaymentCreateRequest : IdempotentRequest
    {
        /// <summary>
        /// Payer information including identification, email, and address.
        /// </summary>
        /// <seealso cref="PaymentPayerRequest"/>
        public PaymentPayerRequest Payer { get; set; }

        /// <summary>
        /// When set to <c>true</c>, the payment can only be approved or rejected.
        /// Otherwise, the "in_process" status is also possible.
        /// </summary>
        public bool? BinaryMode { get; set; }

        /// <summary>
        /// Order associated with this payment.
        /// </summary>
        /// <seealso cref="PaymentOrderRequest"/>
        public PaymentOrderRequest Order { get; set; }

        /// <summary>
        /// External reference ID assigned by the merchant in their own system,
        /// used to reconcile the payment with internal records.
        /// </summary>
        public string ExternalReference { get; set; }

        /// <summary>
        /// Payment reason or item title displayed to the payer.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Arbitrary key-value metadata attached to the payment to store additional
        /// merchant-specific attributes.
        /// </summary>
        public IDictionary<string, object> Metadata { get; set; }

        /// <summary>
        /// Total amount to be paid by the buyer. This is the gross transaction amount.
        /// </summary>
        public decimal? TransactionAmount { get; set; }

        /// <summary>
        /// Net amount received by the seller after fees are deducted.
        /// </summary>
        public decimal? NetAmount { get; set; }

        /// <summary>
        /// Discount amount applied from a coupon, subtracted from the transaction amount.
        /// </summary>
        public decimal? CouponAmount { get; set; }

        /// <summary>
        /// Identifier of the discount campaign to apply to this payment.
        /// </summary>
        public int? CampaignId { get; set; }

        /// <summary>
        /// Coupon code string for a discount campaign.
        /// </summary>
        public string CouponCode { get; set; }

        /// <summary>
        /// Identifier of the differential pricing scheme for absorbing financing fees.
        /// </summary>
        public int? DifferentialPricingId { get; set; }

        /// <summary>
        /// Fee amount collected by a marketplace or MercadoPago application on behalf of the seller.
        /// </summary>
        public decimal? ApplicationFee { get; set; }

        /// <summary>
        /// Determines whether the payment should be captured immediately (<c>true</c>)
        /// or only authorized and reserved for later capture (<c>false</c>).
        /// </summary>
        public bool? Capture { get; set; }

        /// <summary>
        /// Identifier of the payment method chosen for this payment (e.g., "visa", "master", "pix", "bolbradesco").
        /// </summary>
        public string PaymentMethodId { get; set; }

        /// <summary>
        /// Identifier of the payment method issuer (e.g., the issuing bank for a credit card).
        /// </summary>
        public string IssuerId { get; set; }

        /// <summary>
        /// Tokenized card identifier generated by the MercadoPago SDK on the client side.
        /// Required for card payments.
        /// </summary>
        public string Token { get; set; }

        /// <summary>
        /// Text that will appear on the payer's card statement (e.g., "MERCADOPAGO").
        /// </summary>
        public string StatementDescriptor { get; set; }

        /// <summary>
        /// Number of installments selected by the payer. Must be 1 for single payments.
        /// </summary>
        public int? Installments { get; set; }

        /// <summary>
        /// URL where MercadoPago will send webhook notifications for status changes on this payment.
        /// </summary>
        public string NotificationUrl { get; set; }

        /// <summary>
        /// URL where MercadoPago will redirect the payer after completing the payment flow
        /// (applicable to bank transfers and redirect-based payment methods).
        /// </summary>
        public string CallbackUrl { get; set; }

        /// <summary>
        /// Processing mode that defines whether a specific merchant account should be used.
        /// Possible values: "aggregator" (default), "gateway".
        /// </summary>
        public string ProcessingMode { get; set; }

        /// <summary>
        /// Merchant account identifier for gateway mode or complex payment scenarios.
        /// </summary>
        public string MerchantAccountId { get; set; }

        /// <summary>
        /// Expiration date and time for the payment. After this date, the payment
        /// will be automatically cancelled if still pending.
        /// </summary>
        public DateTime? DateOfExpiration { get; set; }

        /// <summary>
        /// Sponsor (platform) identifier for marketplace payment splits.
        /// </summary>
        public long? SponsorId { get; set; }

        /// <summary>
        /// Identifier of a specific payment method option, used when multiple options
        /// exist for the same payment method.
        /// </summary>
        public string PaymentMethodOptionId { get; set; }

        /// <summary>
        /// Marketplace identifier. Defaults to "NONE" for direct integrations.
        /// </summary>
        public string Marketplace { get; set; }

        /// <summary>
        /// Transaction detail information, such as the financial institution for bank transfers.
        /// </summary>
        /// <seealso cref="PaymentTransactionDetailsRequest"/>
        public PaymentTransactionDetailsRequest TransactionDetails { get; set; }

        /// <summary>
        /// Additional information that improves fraud analysis and payment conversion rates.
        /// Sending as much data as possible is strongly recommended.
        /// </summary>
        /// <seealso cref="PaymentAdditionalInfoRequest"/>
        public PaymentAdditionalInfoRequest AdditionalInfo { get; set; }

        /// <summary>
        /// Point of interaction data describing the context in which the payment originates
        /// (e.g., a physical POS terminal or an online checkout).
        /// </summary>
        /// <seealso cref="PaymentPointOfInteractionRequest"/>
        public PaymentPointOfInteractionRequest PointOfInteraction { get; set; }

        /// <summary>
        /// List of taxes applied to this payment.
        /// </summary>
        /// <seealso cref="PaymentTaxRequest"/>
        public IList<PaymentTaxRequest> Taxes { get; set; }

        /// <summary>
        /// Amount breakdown for the collector (seller) and payer, including currency details.
        /// </summary>
        /// <seealso cref="PaymentAmountsRequest"/>
        public PaymentAmountsRequest Amounts { get; set; }

        /// <summary>
        /// Counter currency details used for cross-border payment scenarios.
        /// </summary>
        /// <seealso cref="PaymentCounterCurrencyRequest"/>
        public PaymentCounterCurrencyRequest CounterCurrency { get; set; }

        /// <summary>
        /// Merchant-level services configuration, such as fraud scoring and manual review options.
        /// </summary>
        /// <seealso cref="PaymentMerchantServicesRequest"/>
        public PaymentMerchantServicesRequest MerchantServices { get; set; }

        /// <summary>
        /// Payment method details including type and associated data (e.g., rules for discounts and fees).
        /// </summary>
        /// <seealso cref="PaymentMethodRequest"/>
        public PaymentMethodRequest PaymentMethod { get; set; }

        /// <summary>
        /// 3D Secure mode for card payments. Possible values: "optional", "mandatory", "not_supported".
        /// </summary>
        public string ThreeDSecureMode { get; set; }

        /// <summary>
        /// Forward data request containing sub-merchant and network transaction information.
        /// </summary>
        /// <seealso cref="PaymentForwardDataRequest"/>
        public PaymentForwardDataRequest PaymentForwardDataRequest { get; set; }

        /// <summary>
        /// Forward data containing sub-merchant details and network transaction data
        /// used for payment facilitator flows.
        /// </summary>
        /// <seealso cref="PaymentForwardDataRequest"/>
        public PaymentForwardDataRequest ForwardData { get; set; }
    }
}

