name: CD

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore src/MercadoPago/MercadoPago.csproj

      - name: Build and pack
        run: dotnet pack src/MercadoPago/MercadoPago.csproj --configuration Release --no-restore --output ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
