name: CD

on:
  workflow_run:
    workflows: [ CI ]
    branches: [ master ]
    types:
      - completed

jobs:
  publish:
    name: Publish on NuGet
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build and Pack
        run: dotnet pack src/MercadoPago/MercadoPago.csproj --configuration Release --output ./nupkg

      - name: Publish on NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate