name: CD

on:
  workflow_run:
    workflows: [ CI ]
    branches: [ master ]
    types:
      - completed

jobs:
  publish:
    name: Publish on NuGet
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v7

      - name: Setup dotnet
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v6
        with:
          dotnet-version: '8.0.x'

      - name: Build and Pack
        run: dotnet pack src/MercadoPago/MercadoPago.csproj --configuration Release --output ./nupkg

      - name: Publish on NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate