name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and run tests
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v7

      - name: Setup dotnet
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v6
        with:
          dotnet-version: '8.0.x'

      # Build
      - name: Install dependencies
        run: dotnet restore src/MercadoPago/MercadoPago.csproj

      - name: Build
        run: dotnet build src/MercadoPago/MercadoPago.csproj --configuration Release --no-restore

      # Run Tests
      - name: Install tests dependencies
        run: dotnet restore src/MercadoPago.Tests/MercadoPago.Tests.csproj

      - name: Run tests
        run: dotnet test src/MercadoPago.Tests/MercadoPago.Tests.csproj -f net8.0 --configuration Release --no-restore
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}

      - name: Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5
        with:
          fail-on-severity: high
