// API version: d0494f1c-8d81-4c76-ae1d-0c65bb8ef6de

namespace MercadoPago.Client.Order
{
    /// <summary>
    /// Describes the payment method used in a specific transaction payment, including
    /// card tokenization, installment selection, and billing statement details.
    /// </summary>
    /// <seealso cref="OrderPaymentRequest"/>
    public class OrderPaymentMethodRequest
    {
        /// <summary>
        /// Payment method identifier (e.g., "visa", "master", "pix", "bolbradesco").
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Payment method type (e.g., "credit_card", "debit_card", "bank_transfer", "ticket").
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// Tokenized card identifier generated by the MercadoPago SDK on the client side.
        /// Required for card-based payments.
        /// </summary>
        public string Token { get; set; }

        /// <summary>
        /// Text that appears on the payer's card statement (e.g., "MERCADOPAGO").
        /// </summary>
        public string StatementDescriptor { get; set; }

        /// <summary>
        /// Number of installments selected by the payer for this payment.
        /// Only applicable to payment methods that support installments (e.g., credit cards).
        /// Leave null for payment methods that do not support installments (e.g., Pix, bank transfer).
        /// </summary>
        public int? Installments { get; set; }

        /// <summary>
        /// Financial institution code (required for PSE in Colombia, e.g. "1007" Bancolombia).
        /// </summary>
        public string FinancialInstitution { get; set; }
    }

}
